sdk:
  version: 1.0.0
  retry_policy:
    max_retries: 5
    backoff_factor: 2
  timeout: 30
  logging:
    level: INFO
    enable_file_logging: true
  endpoints:
    auth: /auth
    train: /train
    deploy: /deploy
